services:	
  web:
    container_name: web-interface
    image: node:lts
    user: "node"
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
      SESSION_SECRET: "super duper secret!"
      API_KEY: "ZjGXIfaEG1G4OkSHyB5wvqOQ5BPb9iav"
    ports:
      - "3003:3000"
    volumes:
      - .:/home/node/app # Mount Client directory
      - ./node_modules:/home/node/app/node_modules # Mount node_modules directory
    command: "npm run start"

volumes:
  database:
