services:
  db:
    container_name: gys-db
    image: postgres:14
    environment:
      POSTGRES_USER: "${DB_USER}" # Use DB_USER from .env
      POSTGRES_PASSWORD: "${DB_PASSWORD}" # Use DB_PASSWORD from .env
      POSTGRES_DB: "${DB_NAME}" # Use DB_NAME from .env
    ports:
      - "${DB_PORT}:5432" # Map DB_PORT from .env to internal PostgreSQL port 5432
    volumes:
      - ./database/init-data:/docker-entrypoint-initdb.d
      - users-database:/var/lib/postgresql/data
    env_file:
      - .env # Load all environment variables from .env
    networks:
      - nginx-network

  web:
    container_name: gys-web-interface
    image: node:lts
    user: "${NODE_USER}"
    working_dir: /home/node/app
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - .:/home/node/app # Mount Client directory
      - ./node_modules:/home/node/app/node_modules # Mount node_modules directory
    command: "npm run start"
    env_file:
      - .env # Load all environment variables from .env
    networks:
      - nginx-network

volumes:
  users-database:

networks:
  nginx-network:
    external: true