CREATE TABLE tasks (
    TaskID SERIAL PRIMARY KEY,
    UserID INT REFERENCES users(UserID) ON DELETE CASCADE,
    TaskName VARCHAR(255) NOT NULL,
    Points INT NOT NULL,
    IsCompleted BOOLEAN DEFAULT FALSE
);